### ISSUE TITLE
Error in publisher on writing sample #296

### ISSUE THREAD

**Issue by kallikarls** [rticommunity/rticonnextdds-connector-cs#1]
An error occurs in the publisher when writing sample #296.  Following error is shown on the console:

Writing sample 297
RTILuaContainer_Out:!function 'write' failed with retcode 10
RTI_Connector_write:!Write operation failed with  10
Writing sample 298
RTILuaContainer_Out:!function 'write' failed with retcode 10
RTI_Connector_write:!Write operation failed with  10
Writing sample 299
RTILuaContainer_Out:!function 'write' failed with retcode 10
RTI_Connector_write:!Write operation failed with  10

**Comment by samuelraeburn** [comment]
I believe I know why this is happening.

In your XML file which defines the DDS entities, I guess that the Publisher and Subscriber are defined under the same DomainParticipant. Since (and I am also guessing) that you are using Reliable communication, the DataWriter is keeping some samples in its queue, in case it needs to resend them.

The issue comes from that fact that when you load the Connector object in your Publishing application, a Subscriber (which is defined under the same participant) is also created. Since this Subscriber (which you probably don't want to exist anyway) never takes() the data, the Publisher never removes the samples from its queue.

The solution is to split your XML file such that there are two DomainParticipants, one containing the Publisher and the other containing the Subscriber. Then, in the publishing application load one of the DomainParticipants, and in the subscribing application load the other - make sense?

Let me know if that helps,
Sam

**Comment by kallikarls** [comment]
Bingo! I split the config for the publisher and subscriber participants in the XML file and that worked fine. Thank you very much for the prompt response :)
I'm doing an evaluation of DDS for use with .NET Core.  I did notice that RTI Connext has library for .NET but that to my understanding, this is limited for the .NET Framework, not .NET Core.  Would you happen to know which options there are for DDS and .NET Core at the moment.

Best regards,
Karl

**Comment by samuelraeburn** [comment]
Good to hear :)

With regards to .NET Core support, your understanding of the current RTI Connext library for .NET is correct, it only runs on Windows and doesn't support .NET Core. We have started developing a new RTI Connext .NET Core API. The tentative plan for the new API is to have something ready by the end of the calendar year.

**Comment by Meetsch** [comment]
> We have started developing a new RTI Connext .NET Core API. The tentative plan for the new API is to have something ready by the end of the calendar year.

@samuelraeburn That's a GREAT news, we're also waiting on a .NET Core API !
We currently have a C++/CLI layer which is disallowing us to be completely .NET Core in our C# apps, therefore RTI Connext DDS is the last remaining library which is holding us on windows for our C# apps. Thanks RTI for moving on .NET Core, really appreciated.

**Comment by kallikarls** [comment]
Issue solved with answer from @samuelraeburn . Closing issue.
